partition_disjoint_bigfcup lemma
math-comp/finmap pull request #75
Opened 2020-09-28 06:47 UTC by affeldt-aist

- on the model of the eponymous lemma in finset

2020-09-28 07:20 UTC, affeldt-aist commented
Builds with Coq 8.7, 8.8, 8.9 failing.

2020-09-28 07:28 UTC, pi8027 commented on finmap.v
> +rewrite -Ee in Ae; move: (ih _ Ee ue) => {}ih.
To make it compatible with Coq 8.7, you have to write:
```suggestion
rewrite -Ee in Ae; move: (ih _ Ee ue) => {ih} ih.
```

2020-11-03 10:48 UTC, CohenCyril requested changes
I realize I never sent this piece of review... (still pending)

2020-11-27 09:30 UTC, CohenCyril approved these changes

2020-11-27 09:31 UTC, merged